import type { WatchItem } from './types';

// Mirrors csmoney-links.cjs and tradeit-links.cjs exactly (same query params,
// same reasoning) — computed here instead of re-generated by the bot, since
// the dashboard already has the watch data synced. See those two files for
// why each param is there; this is not a re-derivation, just a port.

function csmoneySearchTerm(name: string): string {
  return name
    .replace(/\|/g, ' ')
    .replace(/[^\w\s.\-']/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

export function csmoneyLink(w: WatchItem): string {
  const q = new URLSearchParams();
  q.set('search', csmoneySearchTerm(w.name));
  q.set('order', 'asc');
  q.set('sort', 'price');
  q.set('maxPrice', String(w.maxPrice));
  q.set('exterior', w.exterior);
  if (w.stattrak) q.set('isStatTrak', 'true');
  if (w.maxFloat != null) q.set('maxFloat', String(w.maxFloat));
  return `https://cs.money/market/buy/?${q.toString()}`;
}

export function tradeitLink(w: WatchItem): string {
  const hashName = `${w.stattrak ? 'StatTrak™ ' : ''}${w.name} (${w.exterior})`;
  const q = new URLSearchParams();
  q.set('search', hashName);
  return `https://tradeit.gg/csgo/store?${q.toString()}`;
}
