import type { WatchItem } from './types';

// Mirrors csmoney-links.cjs and tradeit-links.cjs exactly (same query params,
// same reasoning) — computed here instead of re-generated by the bot, since
// the dashboard already has the watch data synced. See those two files for
// why each param is there; this is not a re-derivation, just a port.

function csmoneySearchTerm(name: string): string {
  return name
    .replace(/\|/g, ' ')
    .replace(/[^\w\s.\-']/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

export function csmoneyLink(w: WatchItem): string {
  const q = new URLSearchParams();
  q.set('search', csmoneySearchTerm(w.name));
  q.set('order', 'asc');
  q.set('sort', 'price');
  q.set('maxPrice', String(w.maxPrice));
  q.set('exterior', w.exterior);
  if (w.stattrak) q.set('isStatTrak', 'true');
  if (w.maxFloat != null) q.set('maxFloat', String(w.maxFloat));
  return `https://cs.money/market/buy/?${q.toString()}`;
}

export function tradeitLink(w: WatchItem): string {
  const hashName = `${w.stattrak ? 'StatTrak™ ' : ''}${w.name} (${w.exterior})`;
  const q = new URLSearchParams();
  q.set('search', hashName);
  return `https://tradeit.gg/csgo/store?${q.toString()}`;
}

// DMarket's own marketplace filters, read off a real filtered URL rather than
// guessed (checked live 2026-09-09 by driving their filter panel and watching
// what the site kept in the address bar):
//
//   title      loose text search. The `|` is stripped — DMarket's search box
//              never emits one, and the site matches fine without it. The
//              StatTrak™ prefix DOES work here and is how StatTrak is
//              narrowed, since the Quality filter is not URL-addressable.
//   exterior   the exterior name LOWERCASED VERBATIM — `minimal wear`, not
//              `minimal-wear`. This one is a trap: DMarket takes a
//              comma-separated list here and silently ignores any token it
//              does not know, so a slugified `minimal-wear` loads a page with
//              no exterior filter at all and no error — it just quietly shows
//              every wear. `field-tested` only appears to work as a slug
//              because the real name already has that hyphen. Verified by
//              clicking the site's own checkboxes and reading back what it
//              put in the address bar.
//   price-to   max price in DOLLARS (not cents, unlike DMarket's API).
//
// Two things deliberately absent, because DMarket strips them from the URL:
// there is no float param (`float-to` was dropped on load, verified), and sort
// order is held in site state, so these open unsorted. The float ceiling still
// has to be set by hand on the page — same caveat the Tradeit link already has.
export function dmarketLink(w: WatchItem): string {
  const title = `${w.stattrak ? 'StatTrak™ ' : ''}${w.name}`.replace(/\s*\|\s*/g, ' ');
  const q = new URLSearchParams();
  q.set('title', title);
  q.set('exterior', w.exterior.toLowerCase());
  q.set('price-to', String(w.maxPrice));
  return `https://dmarket.com/ingame-items/item-list/csgo-skins?${q.toString()}`;
}

// LIS-Skins per-item category page — the slug is a straight port of
// `lisskinsUrl()` in skin-sniper/src/util.cjs, which is the builder the bot's
// own alerts use. The slug is still the WHOLE addressing scheme for the name
// and exterior: LIS-Skins silently ignores a `?search=` query param
// (confirmed there on 2026-07-27), so name/exterior only ever land through
// the slug, never a param.
//
// float_to / price_to (and float_from / price_from) are a different thing and
// DO work as real query params on top of that slug — confirmed live
// 2026-09-12 by filling the site's own Float/Price filter fields and reading
// what it kept in the address bar, then round-tripped by loading that exact
// URL cold: every returned row was inside the bound (float_to=0.27 returned
// rows 0.240-0.269, nothing above). Loading `?search=` and loading these
// filter params are not the same claim — the first is still false, the
// second is now verified true. Only the "to" ceilings are set here since a
// watch only carries a max float/price, no floor.
function lisSlug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

export function lisskinsLink(w: WatchItem): string {
  const prefix = w.stattrak ? 'stattrak-' : '';
  const q = new URLSearchParams();
  q.set('price_to', String(w.maxPrice));
  if (w.maxFloat != null) q.set('float_to', String(w.maxFloat));
  return `https://lis-skins.com/market/csgo/${prefix}${lisSlug(w.name)}-${lisSlug(w.exterior)}/?${q.toString()}`;
}

// Steam Community Market, by exact market_hash_name. This is a PATH segment,
// so it is encodeURIComponent'd rather than built with URLSearchParams — the
// latter would emit `+` for spaces, which is only correct in a query string.
//
// Caveat worth knowing before "fixing" this (checked live 2026-09-09): Steam is
// rolling out a grouped market UI, and under it every wear of a skin redirects
// to ONE shared page (all five exteriors of M4A4 | Etch Lord, StatTrak or not,
// answered with the same `/listings/730/G1810208D093004`), where the exterior
// is a tab rather than part of the URL. So on the new UI this opens the right
// skin but not necessarily the right wear.
//
// The market SEARCH page was tried instead and is worse, not better: its
// `category_730_Exterior[]=tag_WearCategory2` / `category_730_Quality[]=
// tag_strange` params are honoured by Steam's own search data endpoint but
// ignored by the new UI (verified — it rendered them with zero filters
// checked), and it returns a grouped card with no per-wear price. The
// hash-name URL at least still carries the full variant, so it lands exactly
// right for anyone on the classic UI. Don't swap it for a search link.
//
// There is deliberately no price ceiling here. Steam has no max-price param,
// and the watch's `maxPrice` is USD while these Steam wallets are PHP — a
// number carried across would be wrong by ~61x. See the currency note in the
// Desktop CLAUDE.md.
export function steamLink(w: WatchItem): string {
  const hashName = `${w.stattrak ? 'StatTrak™ ' : ''}${w.name} (${w.exterior})`;
  return `https://steamcommunity.com/market/listings/730/${encodeURIComponent(hashName)}`;
}
